### ISSUE TITLE
Browser testing: Latest Firefox

### ISSUE THREAD

**Issue by eads** [nprapps/syria#12]

**Comment by livlab** [comment]
First pass (OSX Yosemite - Desktop Firefox 35.0.1) - Not opening issues for each item because it's just a first pass. Will open issues once I give it another pass after the app is more ready:
1. Main: background image loads slowly on first visit so text is not legible during load (if this is ok loading, perhaps a different background color for contrast could satisfy this).
2. Clicking [BEGIN] scrolls down to The Situation, but it doesn't stop at the right point, still showing some of the image above the title of the chapter:
   ![screenshot 2015-02-10 15 33 08](https://cloud.githubusercontent.com/assets/1936365/6135876/37ed91d6-b13a-11e4-8266-3db60a09a9de.png)
3. All chapters: Linked quote at the bottom does not look like a link; on hover cursor does not change to indicate its linked and color also doesn't indicate its a link (the link does work though).
4. Greece: 4th and 5th images lack a caption.
5. Germany: 5th, 6th, 8th and 9th images lack a caption.
6. Russia: 2nd, 3rd, 6th and 7th images lack a caption.
7. Russia: Lacks call to action at the end.

**Comment by livlab** [comment]
Issues #92 #94 #95 #96 #97 #98 #99 opened.

**Comment by livlab** [comment]
Opened #139 and #145.
