### ISSUE TITLE
Browser testing: Latest Chrome

### ISSUE THREAD

**Issue by eads** [nprapps/syria#13]

**Comment by livlab** [comment]
First pass (OSX Yosemite - Desktop Chrome 40.0.2214.95) - Not opening issues for each item because it's just a first pass. Will open issues once I give it another pass after the app is more ready:
1. Main: background image loads slowly on first visit so text is not legible during load (if this is ok loading, perhaps a different background color for contrast could satisfy this).
2. All chapters: Linked quote at the bottom does not look like a link; on hover cursor does not change to indicate its linked and color also doesn't indicate its a link (the link does work though).
3. Greece: 4th and 5th images lack a caption.
4. Germany: 5th, 6th, 8th and 9th images lack a caption.
5. Russia: 2nd, 3rd, 6th and 7th images lack a caption.
6. Russia: Lacks call to action at the end.

**Comment by livlab** [comment]
Issues #92 #94 #95 #97 #98 #99 opened.

**Comment by livlab** [comment]
No new issues during 3rd pass.
