### ISSUE TITLE
Device testing: Android phone

### ISSUE THREAD

**Issue by eads** [nprapps/syria#18]

**Comment by livlab** [comment]
First pass (Android Chrome) - Not opening issues for each item because it's just a first pass. Will open issues once I give it another pass after the app is more ready:
1. Main: background image loads slowly on first visit so text is not legible during load (if this is ok loading, perhaps a different background color for contrast could satisfy this).
2. The Situation: 2nd image did not load
3. When rotating to landscape everything works well, but returning to portrait creates an odd blank space with everything else scrolling above it.
   ![screenshot_2015-02-10-14-26-57](https://cloud.githubusercontent.com/assets/1936365/6134842/185ca9d6-b132-11e4-8c7c-384267c89ec3.png)

**Comment by livlab** [comment]
Issues #92 #93 #94 #95 #97 #98 #99 opened.

**Comment by livlab** [comment]
Opened #140 and #144
