### ISSUE TITLE
Update Facebook Open Graph tags

### ISSUE THREAD

**Issue by eads** [nprapps/syria#2]
Images should have an aspect ratio of 1.91:1 and be a minimum of 1200 x 630. Verify with debugger: https://developers.facebook.com/tools/debug/

working w/ @kainazamaria

**Comment by beckylettenberger** [comment]
Suggestions:

Over 11 million Syrians have been displaced since civil war broke out. Meet four families struggling to stay together. 

Dalaa al-Aydi,4, has one memory of her Damascus -- the sound of gun fire. She is one of more than 200,000 Syrians refugees who have resettled in Europe since civil war broke out.

**Comment by beckylettenberger** [comment]
![syria_facebook](https://cloud.githubusercontent.com/assets/6115291/6195400/b56e3062-b39b-11e4-83c4-1593a4397e44.jpg)

**Comment by kainazamaria** [comment]
Suggestions:

Over 11 million Syrians have been displaced since civil war broke out. It’s the largest refugee crisis in the world today and one of the biggest since World War II. These are four stories of families struggling to stay together.
